// import { AnimatePresence } from "framer-motion";
import { FormProvider } from "@/context";
import { ConfigProvider } from "antd";
import type { Metadata } from "next";
import { Poppins, Roboto } from "next/font/google";
import "./globals.css";
import Template from "./template";

export const poppins = Poppins({
  weight: ["300", "500"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const roboto = Roboto({
  weight: ["300", "500"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Stepper Form",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <AnimatePresence mode="wait" initial={false}> */}
      <ConfigProvider
        theme={{
          token: {
            fontFamily: `${poppins}`,
          },
        }}
      >
        <FormProvider>
          <Template>
            <body className={`${poppins.variable} font-poppins`}>
              {children}
            </body>
          </Template>
        </FormProvider>
      </ConfigProvider>
      {/* </AnimatePresence> */}
    </html>
  );
}
