import { Poppins, Roboto } from "next/font/google";
import "./globals.css";
import Template from "./template";

export const poppins = Poppins({
  weight: ["300", "500"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const roboto = Roboto({
  weight: ["300", "500"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

// export const metadata: Metadata = {
//   title: "Stepper Form",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Stepper Form</title>
        <meta name="Stepper Form" content="Description" />
      </head>

      <Template>
        <body className={`${poppins.variable} font-poppins`}>{children}</body>
      </Template>
    </html>
  );
}
